<?
$aMenuLinks = Array(
    Array(
        "Гарантії",
        "/about/guaranty/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Оплата",
        "/about/pay/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Доставка",
        "/about/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакти",
        "/about/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "3D Моделі",
        "/3d_model/",
        Array(),
        Array(),
        ""
    )
)
?>
