<?
$aMenuLinks = Array(
    Array(
        "Гарантии",
        "/ru/about/guaranty/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Оплата",
        "/ru/about/pay/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Доставка",
        "/ru/about/delivery/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/ru/about/contacts/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "3D Моделі",
        "/ru/3d_model/",
        Array(),
        Array(),
        ""
    )
)
?>
